language: node_js
node_js:
  - "12.15.0"
cache:
directories:
  - node_modules
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install
script:
  - yarn lint
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: bundle
  on:
    branch: master
